### PR TITLE
Add StartWith function

### PR DESCRIPTION
**Pull request by dmitryuk**
Pr adds STARTS_WITH postgres function

### CODE REVIEW

**Comment by dmitryuk** [comment]
cs-fixer fixed

**Comment by dmitryuk** [comment]
cs-fixer failed for files I never touched - we should skip it

**Comment by martin-georgiev** [comment]
> cs-fixer failed for files I never touched - we should skip it

This should be fixed now; however, can you please add a relevant test ([example](https://github.com/martin-georgiev/postgresql-for-doctrine/blob/main/tests/MartinGeorgiev/Doctrine/ORM/Query/AST/Functions/ToJsonTest.php)) for this function and also update the documentation for [Symfony](https://github.com/martin-georgiev/postgresql-for-doctrine/blob/main/docs/INTEGRATING-WITH-SYMFONY.md) and [Laravel](https://github.com/martin-georgiev/postgresql-for-doctrine/blob/main/docs/INTEGRATING-WITH-LARAVEL.md) with a new function?

**Comment by martin-georgiev** [comment]
> all done

Thank you, Alexander ☺️. I will release it next week as a new version.

**Review by martin-georgiev — APPROVED** [review]

**Pull request merged**
