### PR TITLE
Allow PHP 8

### PR DESCRIPTION
**Pull request by massimilianobraglia**
Hey @martin-georgiev, thank you for this lib.
Just allowing php 8 :)

### CODE REVIEW

**Comment by martin-georgiev** [comment]
Thank you @massimilianobraglia. I was planning on doing that over the next weekend - it is nice to have if free now :).

**Comment by massimilianobraglia** [comment]
You're welcome!
Looking at the CI it seems that phpenv does not support PHP 8 at this moment. Or am I missing something?

**Comment by martin-georgiev** [comment]
I'm not hugely surprised tbh. Maybe, for now, the full Travis integration has to stay on 7.4. Adding 8.0 to the PHP versions list is however helpful - it report which are the outstanding blockers.

**Comment by massimilianobraglia** [comment]
Ok, removing from Travis matrix then!

**Comment by martin-georgiev** [comment]
Ah, 8.0 can stay in the PHP versions list, I was referring to the value of `LATEST_PHP_VERSION` only. At present Travis runs the full CI suite against the PHP version set in that variable. Probably this approach can be revised and change Travis to run against all PHP versions.

**Comment by martin-georgiev** [comment]
[Oh, well...](https://travis-ci.community/t/php-8-0-missing/10132/15)
Looks Travis doesn't have yet PHP 8.0.0 and we may have to reference PHP 8 as 8.0snapshot for the short time being.

**Comment by massimilianobraglia** [comment]
Done :)

**Review by martin-georgiev — APPROVED** [review]

**Comment by martin-georgiev** [comment]
This got released as v1.5.1

**Comment by massimilianobraglia** [comment]
Thank you!

**Pull request merged**
